### ISSUE TITLE
Particle Photon Support

### ISSUE THREAD

**Issue by singlerider** [pkourany/AdafruitPN532_Library#3]
This library does not seem to work appropriately with Particle devices (including the Photon and/or Electron).

I am using the Shield version of the Adafruit PN532 (i2c).

While porting for backwards-compatibility may not be possible, would a version for the newer Particle devices be viable? I have been trying to port my Arduino code for months with zero success.

**Comment by pkourany** [comment]
The library is specifically designed for hardware and software SPI support, not I2C.  The newer version which is on Adafruit's github does support I2C.  I'll look in to porting it and updating my repo in the next few days.

**Comment by antranapp** [comment]
@pkourany did you find some spared time to update the lib with i2c support?. I'm currently trying to use the Grove NFC with I2C.

**Comment by pkourany** [comment]
@peacemoon, I can see you found @Brewskey's library on the Particle forum so I will close this topic and include the [link](https://community.particle.io/t/pn532-nfc-library/18819/10).
